version: "3.3"
services:
  cloudwatchlogs:
    build: .
    image: cloudwatchlogs
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 20M
    ports:
        - "8080:8080"
    restart: never
